### ISSUE TITLE
Is sync (push) towards git sub-directory possible?

### ISSUE THREAD

**Issue by lrozema** [trilbymedia/grav-plugin-git-sync#156]
My entire Grav installation already exists in a git repo alongside Docker build scripts. So the pages exists under ```website/user/pages``` and in the root besides that ```website``` folder exists the .git folder for the checkout. Does the plugin support this and will it be able to push to a branch using that folder structure? While trying to set it up, every time I go to this plugin's config page or every time I save it the wizard will pop back up, is that because of my setup? The test connection did work. How can I set this up properly and/or where can I find some debugging output? Thanks for the help.

**Comment by w00fz** [comment]
Unfortunately the plugin does not support having the full Grav instance in a repository. It is expecting only the user folder to reside on a repository and to be pointed at. This is because traditionally we don't encourage keeping grav on a repository since all that is really needed is the user folder and Grav changes constantly.

That said, there have been different requests about making it possible to support both full instances and just user folders in a repository and I would like to eventually add this functionality, it's just not under my radar for the moment!
