### ISSUE TITLE
Two factor authentication issue?

### ISSUE THREAD

**Issue by redrohX** [trilbymedia/grav-plugin-git-sync#16]
From a security perspective I understand the repo has to be private, but for testing purposes I created a public repo and set up the plugin. 

I'm not 100% sure below error is caused by two-factor authentication, but this occurs after saving the settings in the wizard: `Invalid username or password. fatal: Authentication failed for 'https://redrohX:{password}@github.com/redrohX/md-content.git/'`.

Is it possible to use the plugin with two-factor enabled on a Github account? I'd rather keep two-factor enabled because this is mandatory within the company I work for.

Will it be possible  in the future to connect in a different way to the webhook? Possibly by using the secret key field?

**Comment by Fipo** [comment]
Same issue here ... 
Can't use the plugin because my account must have 2FA ...

**Comment by w00fz** [comment]
To login with a 2FA with Github, you have to generate an Authentication token and then use that one as password instead of the actual account password.
My account is 2FA as well :)

**Comment by w00fz** [comment]
I should probably document this better, please let me know if that works for you.

**Comment by OleVik** [comment]
Using a personal access token with `repo` and `admin:repo_hook` scopes works as password for me.

You can do the same for BitBucket with [App Passwords](https://blog.bitbucket.org/2016/06/06/app-passwords-bitbucket-cloud/). Apart from them calling it an "App Password" and the key being half as long, it works exactly the same: Copy key into password field in plugin-settings, save, sync.

**Comment by w00fz** [comment]
Sweet! I'll need to document all of this or if you feel like putting together a PR, that works too :)

Thanks for checking it that's very useful. Had a feeling it was working out of the box!

**Comment by OleVik** [comment]
I can do a PR for it, though there was one more thing I thought worth checking out: Deployment keys. That is, could we use repository-specific keys rather than all-access ones? It would be another layer of security/specificity.

**Comment by w00fz** [comment]
Unfortunately that is really mostly tied to the server setup more than Git or GitSync themselves. But I think if you follow the steps to set the ssh deploy key on your server and then add the `pub` to the repository, it should be enough to grant access to the machine for git push and pull. 

At this point having GitSync user/pass settings be anything should still work because of the deployment key.
Alternatively I can have an option in GitSync to completely skip the user/password so that it only relies on the RSA.

**Comment by OleVik** [comment]
I think more varied "advanced" options might be advantageous, though as people have remarked, the basic wizard-setup is a strength because setting it up goes very quickly. It might be worth exploring whether the trade-off in difficulty in setup is worth the improved security, or even better if the setup can be simplified to streamline the process. Certainly the access token is barely a small step in addition to the current, I'll compose a PR for it.

As an aside, I already found myself switching between BitBucket and GitHub repos for testing. It would be handy to go from "2-way sync" to "multi-way sync", ie. using multiple origins rather than the one. Switching from radio to checkbox in setup essentially, it would of course require looping over Git commands, though that's not much of an overhead.

**Comment by redrohX** [comment]
Thanks for clearing this up for me guys. Creating a Personal Access Token on Github and setting it to `repo` and `admin:repo_hook` seems to work for me now. Awesome!

**Comment by citizenk** [comment]
Same for GitLab: go to your user settings, find the "Access Tokens" tab and create a token for Git Sync: works very well!

**Comment by w00fz** [comment]
Thanks for testing.

I'm keeping this issue open because @OleVik kindly did a PR (#19) to improve the documentation about 2FA and token access.

I still haven't had the time to go through these but you can expect the next release to have  better documentation from within the wizard.

**Comment by OleVik** [comment]
As noted in the PR, all linguistic changes are merely suggestions for simplification and clarity. The bulk addition is Personal Access tokens with GitHub, BitBucket, and GitLab, which could benefit from being shown conditionally on the selected Git provider in Step 1.

**Comment by w00fz** [comment]
This is now merged in! Thank you all.
