### ISSUE TITLE
fatal error invalid user/password

### ISSUE THREAD

**Issue by millernw** [trilbymedia/grav-plugin-git-sync#176]
I'm getting the following error: 

remote: Invalid username or password. fatal: Authentication failed for 'https://*****%40gmail.com:{password}@github.com/millernw/Grav-testsite-7-2020/'

(note: I replaced my email name with *****, although my login email address does have a '.' - so for example it's firstname.lastname@gmail.com )

When I initially installed the plugin and used the wizard it seemed to accept the user/password but now I'm getting an error. I verified that my email/password for github was correct. 

For what it's worth, I'm using Grav on Linode and under a Caprover install. I don't know if that would affect things or not.

**Comment by w00fz** [comment]
In the Wizard it states that you should use your username, which I am assuming is `millernw`, and not the email address.
That's most likely the reason why it's erroring out.

**Comment by millernw** [comment]
Sorry about that, I tried both ways before posting the problem here (I forgot to mention that in my original post). When I change it back to 'millernw' as my user I get this: 

remote: Invalid username or password. fatal: Authentication failed for 'https://millernw:{password}@github.com/millernw/Grav-testsite-7-2020/'

I should note I do not currently have 2FA installed on github.

**Comment by bricebou** [comment]
Hi,

Since yesterday, I have the exact same issue... I've tried to uninstall and reinstall the plugin, I run the wizard several times (connection seems to work), but when I save a page, I have this error message... I've put my user name and not my email in the plugin configuration.

Thanks in advance !

**Comment by w00fz** [comment]
Make sure you generate an Access Token and use that instead of your password, this is the recommended method for authenticating outside of GitHub nowadays.

`Authentication failed` is not an error coming from GitSync but from the provider and the only reason for that error is the user/pass|token are wrong
