### ISSUE TITLE
future authentication issue with GitSync?

### ISSUE THREAD

**Issue by MattAppleton** [trilbymedia/grav-plugin-git-sync#191]
I just received this notice from GitHub. Sounds like it will affect the plugin's operations after August 13? 

> You recently used a password to access the repository at x_x_x_x_ with git using git/2.17.0.
> 
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by w00fz** [comment]
No this does not affect the plugin. GitSync already supports and has actually been recommending using an access token as password instead of your actual password for a while.

You can generate one by following the instructions on the Wizard (Step 1, select GitHub, you’ll see a description and link about access tokens).

**Comment by MattAppleton** [comment]
Thanks!
