### ISSUE TITLE
Ability to Define a start .gitignore

### ISSUE THREAD

**Issue by coder4life** [trilbymedia/grav-plugin-git-sync#29]
Currently a .gitignore file must be added before commit.

It would be nice during the wizard a default .gitignore template would be included for common types of directory binary files that might appear on various systems. Also the ability to adjust the actual save template for the .gitignore. Upon saving, the .gitignore will become a part of the commit.

**Comment by w00fz** [comment]
On first setup the gitignore gets already automatically created and filled if it doesn't exist already. It has a few entries that are required.

Typically the only reason the gitignore wouldn't be created is if you git cloned a skeleton.

You will always be able to edit the gitignore manually.

I personally think a gitignore editor is a bit beyond the scope of gitsync since it's for advanced users and the most majority of people will always want everything synced.

If this becomes a requested features by many I will consider it.

Cheers!

// Djamil Legato // From iPhone //

**Comment by coder4life** [comment]
I would not go as far as a full editor. Just a simple textbox field with its contents.

I am having a strange issue then that the .gitignore is not being used. I have it included in the user directory, but it seems to get ignored. Unless of course it is not in the right place, but that is a matter of proper documentation.

**Comment by paulhibbitts** [comment]
@coder4life Just to let you know another option might be to adjust the default Blueprints setting, to allow the syncing of additional folders (something planned for possible future releases in the Wizard) - here is more info: https://github.com/trilbymedia/grav-plugin-git-sync/issues/21

**Comment by coder4life** [comment]
So I am finding this plugin a bit troublesome to work with. Only because of some workflow issues associated with it, and when a .gitignore comes into play.

1. OS files are not ignored by default.
2. .gitignore itself is not pushed as part of the git push, especially if a person has needed to make a few custom changes.

Both are changeable after the fact, but not until the commit history has already been polluted with the extra files in history. Some may say this is not a big deal, but if someone did have something custom stuff something more sensitive could be pushed.

One way to fix this is to append the plugin config options to the end of the file instead of replacing the entire file. A simple comment line # Grav plugin Git-Sync ignores.
