### ISSUE TITLE
[Feature request] List remote branches in a dropdown

### ISSUE THREAD

**Issue by coder4life** [trilbymedia/grav-plugin-git-sync#31]
List and configure the remote to track and pull from. The local branches and remote branches could be kept in sync to avoid ambiguity. This would allow more traditional workflows external to Grav. It would be then possible to load different branches for development purposes or prototyping, before using a protected branch that is attached to a live instance.

**Comment by w00fz** [comment]
GitSync doesn't fetch the whole repository and its headers, just the ones specified to keep things faster. This is why you have to manually specify which branch you want to sync from/to.
It's easy enough to just change as needed from the admin even, not many people even ever follow git-flow for their skeleton repositories because it's really just a 'dropbox' more than a repository.

**Comment by coder4life** [comment]
I think you misunderstood my point. It would be great to easily just select box a branch from the remote and create a local branch in sync.
