### ISSUE TITLE
Saving a page becomes slow when enabling plugin.

### ISSUE THREAD

**Issue by karfau** [trilbymedia/grav-plugin-git-sync#51]
Everything works fine in my configuration, but saving a page takes "forever" when the plugin is enabled vs. when I disable it.  
I assume this is because the plugin waits for the git command to finish, before responding.

Is it possible to change something (configuration wise, or by modifying the plugin) to let git do its thing and already respond with the page anyway after it si stored locally?

I'm also thinking about adding a button somewhere to allow the user to store his work when done, instead of on every change, but I couldn't find an option for this either.

Any Ideas welcome, I'm willing to contribute back to the plugin.

Best Christian

**Comment by OleVik** [comment]
On saving: This is because the plugin has to phone the repo. It could be possibly to separate the logic so that saving does a regular filesystem-write of the file, and a background-task handles updating Git. This requires some functionality for performing this in the background, though, which might be tricky to handle robustly.

On storing temporarily: I'm unaware of whether this has made it into Admin, but its been suggested to leverage LocalStorage in the browser to auto-save changes - and of course indicate this with a "Last stored X mins ago" - to allow easier editing without saving. The mechanism has very good cross-browser support now, and is reliable unless the user clears their cache, which would allow writing without saving.

**Comment by karfau** [comment]
In the mean time I added an hourly cronjob calling `bin/plugin git-sync sync`.

But I can imagine it can be valuable to have options for the following:
1. Only commit when saving a file
2. Indicate unpushed changes as a number or just a symbol beside number of pages (like when plugins have updates). For this there should also be an option for the user to do the sync to get rid of the symbol/number.

What do you guys think about this approach?

**Comment by w00fz** [comment]
I was waiting for admin to include an actions area for the sidebar where 3rd party plugins can create their actions that are always available.
With that approach I wanted to make the sync on save optional so that the user could manually sync from the sidebar at wish.

The action bar is something @rhukster and I discussed a while back and the slow saving of gitsync is what inspired it.

**Comment by karfau** [comment]
Cool, just say a word if there is anything I can help with.

**Comment by AmauryCarrade** [comment]
>I was waiting for admin to include an actions area for the sidebar where 3rd party plugins can create their actions that are always available.
>With that approach I wanted to make the sync on save optional so that the user could manually sync from the sidebar at wish.

Now that this is possible (and even implemented on GitSync side), any updates? I would be interested (and I can do it myself and open a PR if you want). I love this plugin, but I'm a little bit sick of the loading time when I save a page…

**Comment by AmauryCarrade** [comment]
Sounds great! By looking at the code, I was to submit a PR somewhat like your code (with a few differences like disabling sync for all CRUD operations, not only saves). I could use your code as a base to spare me some time, if you're okay with that :)

**Comment by paulhibbitts** [comment]
Thanks for the PR!

**Comment by AmauryCarrade** [comment]
I submitted the PR, do what you want with it :p
