### ISSUE TITLE
Push the pages directly at the root of the repo

### ISSUE THREAD

**Issue by Anthodev** [trilbymedia/grav-plugin-git-sync#54]
Hello,

I would like to know if it's possible to have an option to sync the content of the user/pages folder and not the user/pages folder itself at the root of a repo.

I versioned grav on an internal git server but i'd like to allow anyone to pull request the content of the pages to improve them. So actually i can't versioned grav and the pages at the same time.

Thank you!

**Comment by karfau** [comment]
Hey @Anthodev , 

actually there are multiple ways to have separate git repos inside each other.
The one I found most flexible for grav and which I'm using myself,
is to have one repo for everything beside the pages folder (so I `.gitignore` the pages folder), 
and a second repo for the pages.

Other options to do that is git submodules, but as far as I understood this always pins the included repo to a fixed revision.

There are even more options, I think one is called subtree if I recall directly, but i forgot what the difference was. I personnally haven't worked with either of them so far, the gitignore and separete repos always worked great for me.

About the use of grav-plugin-git-sync, I'm not sure I understood your question correctly, 
but there is some discussion in existing open issues, requesting/ suggesting if it should be possible to let pages be the root of the repo the plugin manages, instead of the user folder. See #34 , #25  and others.

Did that answer your question?
If not may be try to explain a bit more?

Best Christian
(not a maintainer of this plugin)

**Comment by Anthodev** [comment]
Hello @karfau,

Sorry for not answering before. So yes i can have multiple repo in the same project (root & pages folder) except with git-sync i'm unable to versioned the folder like config/data/plugins/etc... because of the gitignore in user/

Can you share your gitignore to be able to version all the folder in user/ in the main repo while at the same time to version the pages files in the github repo? Thanks :)

**Comment by karfau** [comment]
Of course: 
in my project directory I have the following one:
```
.idea/
*.iml

# Composer
.composer

# Sass
.sass-cache

# Grav Specific
/*.md
/.htaccess
/.htpasswd
/env/.active
/env/.active.log
/composer.*

backup/*
!backup/.*
cache/*
!cache/.*
assets/*
!assets/.*
logs/*
!logs/.*
images/*
!images/.*

# user folder has own .gitignore

webserver-configs

# OS Generated
.DS_Store*
ehthumbs.db
Icon?
Thumbs.db
*.swp

tests/_output/*
tests/_support/_generated/*
tests/cache/*
tests/error.log

.releases
```
then I have one placed in the user folder: `user/.gitignore`
```
# accounts need to be env specific
/accounts/*
!/accounts/.git*

# not sure about this one
/data/*
!/data/.git*

# pages is own repo:
/pages

# from the grav repo
*/config/security.yaml
config/security.yaml
```
The plugin also creates a `.gitignore` in the user directory if there is noe to be able to use the user folder as its repo root. I dropped that one and created the above one. But I also modified the plugin in (my fork)[karfau/grav-plugin-git-sync] to have `user/pages` as the root of the repo that the plugin is managing.

Hope that helps, otherwise lets continue the conversation in whatever pace works for you :)

Best Christian

**Comment by JLehtinen** [comment]
Adding a request for an option to do what Christian's fork above is doing: use `user/pages` as the root of the repo, so the git-sync content repo could be used as a subtree of the main Grav repo.

**Comment by aerni90** [comment]
@karfau I'm trying to get my head around your solution with two separate repos for the Grav installation and the user/pages folder in conjunction with your fork of git-sync. I don't quite get it yet. Do you mind giving me a step for step rundown from setting up the two git repos with the respective .gitignore file to the plugin configuration on the live server?

Right now I have two repos. One for the whole Grav installation and one for 'user/pages' (also tried it with 'user') When setting up your git-sync fork on the live server I use the 'user/pages' repo. I always get this error: fatal: pathspec 'pages' did not match any files.

Thank you!

**Comment by lianhuilui** [comment]
Sorry, I have this "problem" too. I don't understand why this plugin is doing this with default settings, seeing as how `user/pages` is the default folder for content..

Furthermore, I am noticing that my content in `user/pages` is left modified but not committed, which means after I `git pull` from my local machine, it just dumps the new content in `pages`. I would have to copy and override `pages` to `user/pages`. It just seems a little broken and doesn't at all work like the demo videos suggest? Am I missing something important?

**Comment by JLehtinen** [comment]
I read in Grav's Slack yesterday that there'll be a global sync option for Git-Sync, which for me would be a solution. Looking forward to that :)

**Comment by rhukster** [comment]
Global sync button is now available. Need latest admin and git-sync.

**Comment by aerni90** [comment]
@rhukster What does the global sync button do? What folders does it sync?

**Comment by w00fz** [comment]
It performs the same action as  the plugin's button "Synchronize" in the settings or via the cli `bin/plugin git-sync sync`

**Comment by aerni90** [comment]
@w00fz What exactly does the button "Synchronize" do? Does it download the latest repo update of the pages folder?

**Comment by w00fz** [comment]
It’s a git fetch + git commit/push (if any) + git pull of the user folder. If you haven’t manually changed the user folders then it will just do pages.

This same action is performed every time you save a new page and such.

You have a synchronize button in the plugin settings and now also in the admin tray. 
Most of the time you don’t really need to manually use the button but it’s useful when you feel things are out of sync or you decided to not use the web hook etc.

Does it make sense?
