### ISSUE TITLE
Does not sync when website is basic auth protected

### ISSUE THREAD

**Issue by uedaeita** [trilbymedia/grav-plugin-git-sync#85]
It seems like when the website is basic authentication enabled, the git-sync does not work. I have ```http://username:password@website_url/_git-sync``` for my webhook and the webhook returns internal error (Net::ReadTimeout) what's the issue?

**Comment by w00fz** [comment]
This seems to be an issue with your web server more than GitSync, try accessing it yourself via browser and from outside your network (ie, via LTE on your phone). 
The error appears to indicate your site is just not reachable with that user/pass.

I would also suggest rather than passing the authentication via URL like you are doing (which is really not safe), you just allow all the IPs from GitHub servers (https://api.github.com/meta).
