### ISSUE TITLE
Documentation: Need to create local git repository

### ISSUE THREAD

**Issue by bleutzinn** [trilbymedia/grav-plugin-git-sync#9]
When I first installed and had finished the setup by using the Wizard I got a "fatal: Not a git repository (or any of the parent directories): .git" error message in the Admin panel upon a Save action.

It took me a while to figure out that I needed to initialise a local git repository in the "user" folder instead of in the "pages" folder as I assumed, as that is where content is stored.

I think this requirement isn't mentioned anywhere yet, nor in the docs, nor in the video's.
Would it be possible to have the Wizard do the `git init` command if the 'user' folder isn't a git repository?

Thumbs up for this plugin!

**Comment by w00fz** [comment]
This is actually part of the plugin, it does already initialize it for you so something else must going on.
In my setup I tried installing a fresh Grav + Admin instance, then I forked the blog-site skeleton.
The user folder at this point knows nothing about git repositories.
I then installed Git Sync and after having setup user, password and having pointed the plugin to my forked blog-site skeleton, GitSync initialized my user folder and did the initial synchronization.

At this point I had a .git folder in user, there shouldn't be any need to initialize the repository locally and manually.

What steps did you perform?

**Comment by bleutzinn** [comment]
During the configuration of an earlier release of the plugin the wizard got stuck. I updated the plugin from the Admin panel and then was shown the error by git.
When I did an install on a clean Grav site the repository is indeed created.

This issue can be closed, thank you.

**Comment by stephanfriedrich** [comment]
@w00fz  i have an similar issue.
grav-sync wont initiate grav/user with an git repository. 

1] i created an clean grav folder (via my ansible playbook)
2] `bin/gpm install admin`
3] created admin user via grav webinterface
4] `sudo  bin/gpm install git-sync` (sudo because got an error)
_Uncaught exception 'RuntimeException' with message 'Opening file for writing failed on error fopen(grav/cache/compiled/blueprints/master-localhost.php): failed to open stream: Permission denied' in grav/vendor/rockettheme/toolbox/File/src/File.php:202_
5] run grav-sync install wizard on admin-webinterface
5.1] within install wizard, i try "test-connection" to github, an it shows success-dialog
6] after saving the wizard, and a short reload time, it show the wizard again

it seems to me its an file-permission issue
